# Generated by Django 4.0.2 on 2022-04-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
