# Generated by Django 4.0.2 on 2022-04-16 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_blogpost_id_alter_image_id_alter_project_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='project.imagealbum'),
        ),
        migrations.AlterField(
            model_name='project',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectImage', to='project.imagealbum'),
        ),
    ]
