# Generated by Django 4.0.2 on 2022-04-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_image_album_alter_project_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='name',
            field=models.CharField(default='hello', max_length=255),
            preserve_default=False,
        ),
    ]
