# Generated by Django 4.0.2 on 2022-04-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_imagealbum_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='blogImage', to='project.imagealbum'),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='project.imagealbum'),
        ),
        migrations.AlterField(
            model_name='project',
            name='album',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectImage', to='project.imagealbum'),
        ),
    ]
