# Generated by Django 4.0.2 on 2022-04-16 10:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_blogpost_album_alter_image_album_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
